name: Build Docker
on:
    push:
        branches: ['main']
jobs:
    docker:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
 
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Log in to container registry
              uses: docker/login-action@v1.10.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build & push
              uses: docker/build-push-action@v2.6.1
              with:
                  context: .
                  push: true
                  tags: ghcr.io/matrix-org/allchange:latest
